-- Snowpipe Alerts Configuration
-- Run these in Snowflake worksheet after Snowpipe is set up.
-- Requires Snowflake email integration or notification integration.

-- 1. Create notification integration (one-time, run as ACCOUNTADMIN)
-- CREATE NOTIFICATION INTEGRATION email_integration
--   TYPE=EMAIL
--   ENABLED=TRUE
--   ALLOWED_RECIPIENTS=('your-email@example.com');

-- 2. Create alert for Snowpipe load failures
-- CREATE OR REPLACE ALERT agent_metadata_load_failure_alert
--   WAREHOUSE = COMPUTE_WH
--   SCHEDULE = '60 MINUTE'
--   IF (EXISTS (
--     SELECT 1 FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
--       TABLE_NAME => 'AGENT_METADATA_DB.PUBLIC.AGENT_METADATA',
--       START_TIME => DATEADD('hour', -1, CURRENT_TIMESTAMP())
--     ))
--     WHERE STATUS = 'LOAD_FAILED'
--   ))
--   THEN
--     CALL SYSTEM$SEND_EMAIL(
--       'email_integration',
--       'your-email@example.com',
--       'Snowpipe Load Failure',
--       'Agent metadata Snowpipe load has failures. Check COPY_HISTORY.'
--     );

-- 3. Create alert for data freshness (no new data in 24 hours)
-- CREATE OR REPLACE ALERT agent_metadata_stale_alert
--   WAREHOUSE = COMPUTE_WH
--   SCHEDULE = '24 HOUR'
--   IF ((
--     SELECT MAX(ingested_at) FROM AGENT_METADATA_DB.PUBLIC.AGENT_METADATA
--   ) < DATEADD('hour', -24, CURRENT_TIMESTAMP()))
--   THEN
--     CALL SYSTEM$SEND_EMAIL(
--       'email_integration',
--       'your-email@example.com',
--       'Agent Metadata Stale',
--       'No new agent metadata ingested in 24 hours.'
--     );
